// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOqhlgnTTpG-HkM2q8FXSRvzVPQDEKEQI',
    appId: '1:1045978942539:web:334226443630c2a61991ce',
    messagingSenderId: '1045978942539',
    projectId: 'masumbook-404c1',
    authDomain: 'masumbook-404c1.firebaseapp.com',
    storageBucket: 'masumbook-404c1.appspot.com',
    measurementId: 'G-N1P3QNVLP3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZZwT-4B8JFh8LZRoWF6qQniweEeBONlQ',
    appId: '1:1045978942539:android:612b543480766b0e1991ce',
    messagingSenderId: '1045978942539',
    projectId: 'masumbook-404c1',
    storageBucket: 'masumbook-404c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB1FdsaxHO4RBQDUJDbG2Iz_JE9v8z8Tw',
    appId: '1:1045978942539:ios:8a8b314dbabf872c1991ce',
    messagingSenderId: '1045978942539',
    projectId: 'masumbook-404c1',
    storageBucket: 'masumbook-404c1.appspot.com',
    iosBundleId: 'com.example.masumbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB1FdsaxHO4RBQDUJDbG2Iz_JE9v8z8Tw',
    appId: '1:1045978942539:ios:7329f62f4d2122231991ce',
    messagingSenderId: '1045978942539',
    projectId: 'masumbook-404c1',
    storageBucket: 'masumbook-404c1.appspot.com',
    iosBundleId: 'com.example.masumbook.RunnerTests',
  );
}
